version: "2.19"
services:
  web:
    image: jmixtest/jmix-pm
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      APP_USER: admin
      APP_PASSWORD: admin
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: projectmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres